const actiontypes = {
  USER_ADDED: 'USER_ADDED',
  PRODUCT_FETCH: 'PRODUCT_FETCH',
  PRODUCT_FETCHED_SUCCESS: 'PRODUCT_FETCHED_SUCCESS',
  PRODUCT_FETCHED_FAILURE: 'PRODUCT_FETCHED_FAILURE',
  CATEGORY_FETCH: 'CATEGORY_FETCH',
  CATEGORY_FETCH_SUCCESS: 'CATEGORY_FETCH_SUCCESS',
  CATEGORY_FETCH_FAILURE: 'CATEGORY_FETCH_FAILURE',
};

export default actiontypes;
